version: '3.5'

services:
  nginx:
    image: 'nginx:latest'
    volumes:
      - .:/var/www/
      - ./docker/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8000:80'
    restart: unless-stopped
    container_name: rest_api_app_nginx

  php:
    build:
      context: .
      dockerfile: docker/local/php/Dockerfile
    volumes:
      - .:/var/www
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    restart: unless-stopped
    container_name: rest_api_app_php
    entrypoint: ["sh", "/usr/local/bin/entrypoint.sh"]

  pgsql:
    image: 'postgis/postgis:latest'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    container_name: rest_api_app_pgsql
